apiVersion: v1
kind: Service
metadata:
  name: {{ include "netifi-broker.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "netifi-broker.name" . }}
    helm.sh/chart: {{ include "netifi-broker.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.serviceType }}
  selector:
    app.kubernetes.io/name: {{ include "netifi-broker.name" . }}
    helm.sh/chart: {{ include "netifi-broker.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  ports:
    - name: tcp
      port: {{ .Values.tcp.port }}
      protocol: TCP
    - name: websocket
      port: {{ .Values.websocket.port }}
      protocol: TCP
    - name: cluster
      port: {{ .Values.cluster.port }}
      protocol: TCP
    - name: admin
      port: {{ .Values.admin.port }}
      protocol: TCP
    - name: console
      port: {{ .Values.console.port }}
      protocol: TCP
